# Generated by Django 5.2.8 on 2026-01-10 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('panel_type', models.CharField(max_length=50)),
                ('grid_w', models.IntegerField(default=1)),
                ('grid_h', models.IntegerField(default=1)),
                ('chart_options', models.JSONField(default=dict)),
                ('query_config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'panel_id')},
            },
        ),
    ]
